version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - cloud-canvas-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloud_canvas
      MYSQL_USER: cloud_canvas_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cloud-canvas-network

  back:
    image: geonhyukseo/cloud-canvas-server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    container_name: back
    environment:
      DATABASE_URL: mysql://cloud_canvas_user:password@mysql:3306/cloud_canvas
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    entrypoint: sh -c "dockerize -wait tcp://mysql:3306 -timeout 20s && npx prisma migrate dev && node ./dist/src/main.js"
    networks:
      - cloud-canvas-network

  front:
    image: geonhyukseo/cloud-canvas-client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: front
    ports:
      - "5001:5000"
    networks:
      - cloud-canvas-network

networks:
  cloud-canvas-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  mysql-data:
    driver: local
