global:
    scrape_interval: 15s
    evaluation_interval: 15s
scrape_configs:
    - job_name: mysql
      scrape_interval: 5s
      static_configs:
          - targets: ['mysqld_exporter:9104']
    - job_name: redis
      scrape_interval: 5s
      static_configs:
          - targets: ['redis_exporter:9121']
