services:
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 30s
            retries: 3
            start_period: 20s
            timeout: 5s
        logging:
            driver: 'fluentd'
            options:
                fluentd-address: 'localhost:24224'
                fluentd-async-connect: 'true'
                tag: 'redis'
        networks:
            - cloud-canvas-network
            - cloud-canvas-database-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: cloud_canvas
            MYSQL_USER: cloud_canvas_user
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
            - ../config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ../config/mysql/log.cnf:/etc/mysql/conf.d/log.cnf:ro
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        command:
            - sh
            - -c
            - |
                mkdir -p /var/log/mysql && \
                touch /var/log/mysql/general.log && \
                tail -f /var/log/mysql/general.log & \
                exec docker-entrypoint.sh mysqld
        logging:
            driver: 'fluentd'
            options:
                fluentd-address: 'localhost:24224'
                fluentd-async-connect: 'true'
                tag: 'mysql'
        networks:
            - cloud-canvas-network
            - cloud-canvas-database-network
        restart: unless-stopped

    back:
        image: t84ar7xr.kr.private-ncr.ntruss.com/back:dev
        container_name: back
        environment:
            DATABASE_URL: mysql://cloud_canvas_user:password@mysql:3306/cloud_canvas
        ports:
            - '3000:3000'
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        entrypoint: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && node ./dist/src/main.js"
        networks:
            - cloud-canvas-network
        restart: unless-stopped

    front:
        image: t84ar7xr.kr.private-ncr.ntruss.com/front:dev
        container_name: front
        ports:
            - '5001:5000'
        networks:
            - cloud-canvas-network
        restart: unless-stopped

    fluentd:
        build: ./logging/fluentd/
        container_name: fluentd
        volumes:
            - ./logging/fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
        ports:
            - '24224:24224'
            - '24224:24224/udp'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:24224/api/health']
            interval: 30s
            retries: 3
            start_period: 10s
            timeout: 10s
        networks:
            - cloud-canvas-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        container_name: elasticsearch
        environment:
            - 'discovery.type=single-node'
        ports:
            - '9200:9200'
        networks:
            - cloud-canvas-network

    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.1
        container_name: kibana
        ports:
            - '5601:5601'
        networks:
            - cloud-canvas-network

networks:
    cloud-canvas-network:
        driver: bridge
    cloud-canvas-database-network:
        driver: bridge

volumes:
    redis-data:
        driver: local
    mysql-data:
        driver: local
