services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes: 
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cloud-canvas-database-network

  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    command:
      - "--mysqld.username=exporter:password"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cloud-canvas-database-network
  
  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cloud-canvas-database-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "30000:3000"
    networks:
      - cloud-canvas-database-network

networks:
  cloud-canvas-database-network:
    driver: bridge