name: Client CI
on:
    pull_request:
        branches:
            - development
        types: [closed]

concurrency:
    group: cloud-canvas

jobs:
    client-image-build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: NCP registry login
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.NCP_REGISTRY }}
                  username: ${{ secrets.NCP_ACCESS_KEY }}
                  password: ${{ secrets.NCP_SECRET_KEY }}

            - name: Docker front image build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/client/Dockerfile
                  push: true
                  tags: |
                      cloud-canvas.kr.ncr.ntruss.com/front:dev
                      cloud-canvas.kr.ncr.ntruss.com/front:${{ github.sha }}

            - name: Docker back image build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./apps/server/Dockerfile
                  push: true
                  tags: |
                      cloud-canvas.kr.ncr.ntruss.com/back:dev
                      cloud-canvas.kr.ncr.ntruss.com/back:${{ github.sha }}

            - name: SSH login and deploy
              run: |
                  echo ${{ secrets.NCP_DEV_SSH }} > dev_login.pem
                  ssh -i dev_login.pem ncloud@${{ secrets.NCP_DEV_INSTANCE }} -p ${{ secrets.NCP_DEV_INSTANCE_PORT }}
                  ./docker.sh
